[package]
name = "cw-voting"
version = "0.2.1"
authors = ["Taariq Levack <levackt@users.noreply.github.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Simple CosmWasm contract for voting"
repository = "https://github.com/CosmWasm/cosmwasm-examples"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = ["cranelift"]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces", "cosmwasm-vm/backtraces"]
cranelift = ["cosmwasm-vm/default-cranelift"]
singlepass = ["cosmwasm-vm/default-singlepass"]

[dependencies]
cosmwasm-std = "0.11.0-alpha1"
cosmwasm-storage = "0.11.0-alpha1"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
hex = "0.4"
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-vm = { version = "0.11.0-alpha1", default-features = false }
cosmwasm-schema = "0.11.0-alpha1"
